version: '3'
services:
  fava:
    image: quewen08/fava-management
    container_name: 'fava'
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BEANCOUNT_FILE=/bean/main.bean
      - USERNAME=admin
      - PASSWORD=12345678
    volumes:
      - ./data:/bean
